---

- name: Test if azure creds dir exists.
  command: test -d ~{{ azure_cli_role_creds_user }}/.azure
  register: azure_creds_dir_check
  changed_when: false
  ignore_errors: true

- name: "Create .azure dir if existence test fails"
  command: mkdir -p ~{{ azure_cli_role_creds_user }}/.azure
  args:
    warn: no
  become: yes
  become_user: "{{ azure_cli_role_creds_user }}"
  when: azure_creds_dir_check.rc != 0

- name: "Write credentials file out"
  copy:
    dest: "~{{ azure_cli_role_creds_user }}/.azure/credentials"
    content: "{{ azure_cli_role_creds_file_content }}"
  no_log: true
  become: yes
  become_user: "{{ azure_cli_role_creds_user }}"
