---
- name: "Check if v2 already installed"
  command: az
  failed_when: false
  changed_when: false
  register: az_v2_test
  tags:
    - azure-cli

- name: "Copy v2 install script"
  copy:
    src: "files/install.py"
    dest: "/tmp/azure_cli_install.py"
  when: az_v2_test.rc != 0
  tags:
    - azure-cli

- name: "Install v2"
  command: "/bin/python /tmp/azure_cli_install.py"
  when: az_v2_test.rc != 0
  environment:
    http_proxy: "http://reformmgmtproxyout.reform.hmcts.net:8080/"
    https_proxy: "http://reformmgmtproxyout.reform.hmcts.net:8080/"
  tags:
    - azure-cli
